name = "PropertyDestructuring"
uuid = "2286abf2-1405-4c73-bd25-9fea294caf7c"
authors = ["GOTOH Shunsuke <antimon2.me@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"

[compat]
ExprTools = "0.1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
